// services/sql-generator/utils.ts

/**
 * Helper to literalize JavaScript values for SQL
 */
export const literalize = (v: any): string => {
  if (v == null) return "NULL";
  if (typeof v === "string") return `'${v.replace(/'/g, "''")}'`;
  if (typeof v === "object") {
    const js = JSON.stringify(v).replace(/'/g, "''");
    return `'${js}'::jsonb`;
  }
  return v.toString();
};

/**
 * Generate SQL header with metadata
 */
export const generateHeader = (): string => {
  return "-- Generated by Supabase Migration Tool\n" +
         "-- DROP AND RECREATE APPROACH: All selected items will be dropped and recreated\n\n";
};

/**
 * Generate cleanup section header
 */
export const generateCleanupHeader = (): string => {
  return "-- ═══ CLEANUP: DROP EXISTING OBJECTS ═══════════════════════════════════════\n\n";
};

/**
 * Generate recreation section header
 */
export const generateRecreationHeader = (): string => {
  return "-- ═══ RECREATION SECTION: CREATE NEW OBJECTS ═══════════════════════════════════\n\n";
};